#! /bin/sh

# chkconfig: - 99 01
# processname: btsync 

BTSYNC_BIN=/home/btsync/btsync

# Source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog=btsync
config=/home/btsync/btsync.conf
username=btsync

start()
{
    [ $UID -eq 0 ] || exit 4
    [ -x $BTSYNC_BIN ] || exit 5
    [ -f $config ] || exit 6
	echo -n $"Starting $prog: "
	daemon --user=$username $BTSYNC_BIN --config $config
	RETVAL=$?
    echo
	return $RETVAL
}

stop()
{
    [ $UID -eq 0 ] || exit 4
	echo -n $"Shutting down $prog: "
	killproc $BTSYNC_BIN
	RETVAL=$?
    echo
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status|}"
		RETVAL=2
		[ "$1" = 'usage' ] && RETVAL=0
esac

exit $RETVAL

